name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore githubAction.sln
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-build --verbosity normal githubAction.sln
    - name: Publish
      run: dotnet publish githubAction.sln
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0

